name: update_versions.yml
on:
  push:
  schedule:
    - cron: '37 17 * * *'
  workflow_dispatch:

jobs:
  update_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
          pip-install: -r scripts/requirements.txt
      - name: Update versions from Modrinth
        run: python scripts/update_modrinth_versions.py
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          default_author: 'github_actions'
          message: Update versions from Modrinth
